#!/bin/bash
##
: ${GALLERY_FLDR:=gallery}

ag_gmk_write_preamble_check () {
	local preset_autotool_tool_name=${1:-autoconf}
	local preset_autotool_variable_name=${2:-abs_top_srcdir}
	local ancestor_directory_human_name=${3:-parent}
	printf "\$(if \$(%s),,\$(error preset %s variable %s not set, consider to run make from the %s directory))" \
		${preset_autotool_variable_name} ${preset_autotool_tool_name} ${preset_autotool_variable_name} ${ancestor_directory_human_name}
	return 0
	}

if [ -d ${GALLERY_FLDR} ] ; then
	LISTOF_GALLERY_TLLC_FLDR=$(find ${GALLERY_FLDR} -type d -a -regextype posix-extended -regex ${GALLERY_FLDR}'/gallery-en')
#WIP#	LISTOF_GALLERY_TLLC_FLDR=$(find ${GALLERY_FLDR} -type d -a -regextype posix-extended -regex ${GALLERY_FLDR}'/gallery-[a-z]{2}')
	for gal_tllc in ${LISTOF_GALLERY_TLLC_FLDR} ; do
		gallery_collection_data=${gal_tllc}/galleries.txt
		if [ -f ${gallery_collection_data} ]; then
			gnumakefile=${gal_tllc}/GNUmakefile
			if [ -f ${gnumakefile} ]; then
				echo 1>&2 "refresh ${gnumakefile}"
####				mv ${gnumakefile} ${gnumakefile}~
			else
				echo 1>&2 "create  ${gnumakefile}"
			fi
			cat > ${gnumakefile} <<-EOGM
				## ${gnumakefile##*/} generated by ${0}
				$(ag_gmk_write_preamble_check autoconf abs_top_srcdir parent)
				$(ag_gmk_write_preamble_check autoconf abs_top_builddir parent)
				include \$(abs_top_srcdir)/gallery/gallerymakefile.mk
				EOGM
			for collection in $(cat ${gallery_collection_data}) ; do
				collection_fldr=${gal_tllc}/${collection}
				if [ -d ${collection_fldr} ]; then
					gnumakefile=${collection_fldr}/GNUmakefile
					if [ -f ${gnumakefile} ]; then
						echo 1>&2 "refresh ${gnumakefile}"
####						mv ${gnumakefile} ${gnumakefile}~
					else
						echo 1>&2 "create  ${gnumakefile}"
					fi
					cat > ${gnumakefile} <<-EOGM
						## ${gnumakefile##*/} generated by ${0}
						$(ag_gmk_write_preamble_check autoconf abs_top_srcdir grandparent)
						$(ag_gmk_write_preamble_check autoconf abs_top_builddir grandparent)
						include \$(abs_top_srcdir)/gallery/gallerycollectionmakefile.mk
						EOGM
##				else
##					echo 1>&2 "cannot find ${collection_fldr} collection folder"
				fi
			done
##		else
##			echo 1>&2 "cannot find ${gallery_collection_data} collection data"
		fi
	done
fi

autoreconf --force
## eos
