/* XPM */
static char * BMBF_RGB_Gef_M_xpm[] = {
"169 120 294 2",
"  	c #FFFFFF",
". 	c #FEFEFE",
"+ 	c #FDFDFD",
"@ 	c #ABABAB",
"# 	c #B9B9B9",
"$ 	c #F1F1F1",
"% 	c #E6E6E6",
"& 	c #D2D2D2",
"* 	c #FBFBFB",
"= 	c #DEDEDE",
"- 	c #DFDFDF",
"; 	c #EDEDED",
"> 	c #EBEBEB",
", 	c #E1E1E1",
"' 	c #9D9D9D",
") 	c #9C9C9C",
"! 	c #F3F3F3",
"~ 	c #FAFAFA",
"{ 	c #E3E3E3",
"] 	c #F5F5F5",
"^ 	c #E0E0E0",
"/ 	c #ECECEC",
"( 	c #EEEEEE",
"_ 	c #F7F7F7",
": 	c #E9E9E9",
"< 	c #DADADA",
"[ 	c #E2E2E2",
"} 	c #EAEAEA",
"| 	c #E5E5E5",
"1 	c #CECECE",
"2 	c #494949",
"3 	c #818181",
"4 	c #5C5C5C",
"5 	c #EFEFEF",
"6 	c #2F2F2F",
"7 	c #7F7F7F",
"8 	c #B7B7B7",
"9 	c #5F5F5F",
"0 	c #767676",
"a 	c #888888",
"b 	c #C0C0C0",
"c 	c #4F4F4F",
"d 	c #717171",
"e 	c #858585",
"f 	c #CFCFCF",
"g 	c #3F3F3F",
"h 	c #6E6E6E",
"i 	c #656565",
"j 	c #AFAFAF",
"k 	c #484848",
"l 	c #636363",
"m 	c #787878",
"n 	c #272727",
"o 	c #6F6F6F",
"p 	c #676767",
"q 	c #454545",
"r 	c #A8A8A8",
"s 	c #7E7E7E",
"t 	c #262626",
"u 	c #3D3D3D",
"v 	c #D4D4D4",
"w 	c #707070",
"x 	c #8B8B8B",
"y 	c #6D6D6D",
"z 	c #535353",
"A 	c #8F8F8F",
"B 	c #242424",
"C 	c #F9F9F9",
"D 	c #101010",
"E 	c #AEAEAE",
"F 	c #919191",
"G 	c #C3C3C3",
"H 	c #808080",
"I 	c #BFBFBF",
"J 	c #F6F6F6",
"K 	c #4B4B4B",
"L 	c #D0D0D0",
"M 	c #ACACAC",
"N 	c #939393",
"O 	c #616161",
"P 	c #909090",
"Q 	c #BBBBBB",
"R 	c #FCFCFC",
"S 	c #CCCCCC",
"T 	c #8E8E8E",
"U 	c #414141",
"V 	c #737373",
"W 	c #727272",
"X 	c #BABABA",
"Y 	c #606060",
"Z 	c #595959",
"` 	c #7C7C7C",
" .	c #B0B0B0",
"..	c #4D4D4D",
"+.	c #1D1D1D",
"@.	c #2A2A2A",
"#.	c #4E4E4E",
"$.	c #A0A0A0",
"%.	c #585858",
"&.	c #8D8D8D",
"*.	c #969696",
"=.	c #F0F0F0",
"-.	c #5E5E5E",
";.	c #838383",
">.	c #BCBCBC",
",.	c #444444",
"'.	c #505050",
").	c #A2A2A2",
"!.	c #525252",
"~.	c #C9C9C9",
"{.	c #9F9F9F",
"].	c #D9D9D9",
"^.	c #424242",
"/.	c #797979",
"(.	c #545454",
"_.	c #232323",
":.	c #9B9B9B",
"<.	c #CBCBCB",
"[.	c #474747",
"}.	c #949494",
"|.	c #3B3B3B",
"1.	c #353535",
"2.	c #B5B5B5",
"3.	c #878787",
"4.	c #5B5B5B",
"5.	c #4A4A4A",
"6.	c #C5C5C5",
"7.	c #BEBEBE",
"8.	c #929292",
"9.	c #E8E8E8",
"0.	c #343434",
"a.	c #9A9A9A",
"b.	c #E7E7E7",
"c.	c #C4C4C4",
"d.	c #010101",
"e.	c #7D7D7D",
"f.	c #959595",
"g.	c #000000",
"h.	c #0B0B0B",
"i.	c #2E2E2E",
"j.	c #1C1C1C",
"k.	c #0E0E0E",
"l.	c #2D2D2D",
"m.	c #5A5A5A",
"n.	c #F2F2F2",
"o.	c #393939",
"p.	c #555555",
"q.	c #080808",
"r.	c #BDBDBD",
"s.	c #6A6A6A",
"t.	c #222222",
"u.	c #3C3C3C",
"v.	c #0F0F0F",
"w.	c #1F1F1F",
"x.	c #282828",
"y.	c #0D0D0D",
"z.	c #B1B1B1",
"A.	c #7B7B7B",
"B.	c #383838",
"C.	c #5D5D5D",
"D.	c #666666",
"E.	c #8C8C8C",
"F.	c #D5D5D5",
"G.	c #333333",
"H.	c #464646",
"I.	c #C8C8C8",
"J.	c #D3D3D3",
"K.	c #565656",
"L.	c #363636",
"M.	c #040404",
"N.	c #A7A7A7",
"O.	c #404040",
"P.	c #CACACA",
"Q.	c #868686",
"R.	c #C7C7C7",
"S.	c #757575",
"T.	c #323232",
"U.	c #999999",
"V.	c #181818",
"W.	c #313131",
"X.	c #686868",
"Y.	c #F4F4F4",
"Z.	c #626262",
"`.	c #303030",
" +	c #0C0C0C",
".+	c #373737",
"++	c #252525",
"@+	c #898989",
"#+	c #2C2C2C",
"$+	c #B4B4B4",
"%+	c #828282",
"&+	c #212121",
"*+	c #141414",
"=+	c #121212",
"-+	c #9E9E9E",
";+	c #2B2B2B",
">+	c #979797",
",+	c #6C6C6C",
"'+	c #696969",
")+	c #6B6B6B",
"!+	c #1E1E1E",
"~+	c #DCDCDC",
"{+	c #030303",
"]+	c #B2B2B2",
"^+	c #202020",
"/+	c #7A7A7A",
"(+	c #292929",
"_+	c #A4A4A4",
":+	c #1A1A1A",
"<+	c #3E3E3E",
"[+	c #090909",
"}+	c #777777",
"|+	c #151515",
"1+	c #C6C6C6",
"2+	c #020202",
"3+	c #1B1B1B",
"4+	c #070707",
"5+	c #161616",
"6+	c #DBDBDB",
"7+	c #D6D6D6",
"8+	c #747474",
"9+	c #C1C1C1",
"0+	c #CDCDCD",
"a+	c #434343",
"b+	c #E4E4E4",
"c+	c #3A3A3A",
"d+	c #A6A6A6",
"e+	c #0A0A0A",
"f+	c #A3A3A3",
"g+	c #050505",
"h+	c #191919",
"i+	c #646464",
"j+	c #989898",
"k+	c #8A8A8A",
"l+	c #B3B3B3",
"m+	c #848484",
"n+	c #B8B8B8",
"o+	c #A1A1A1",
"p+	c #DDDDDD",
"q+	c #4C4C4C",
"r+	c #C2C2C2",
"s+	c #575757",
"t+	c #FFFFFD",
"u+	c #000100",
"v+	c #5F5F5D",
"w+	c #FEFFFF",
"x+	c #FFFEFF",
"y+	c #AAAAAA",
"z+	c #010000",
"A+	c #5F5F61",
"B+	c #171717",
"C+	c #605E5F",
"D+	c #FEFEFF",
"E+	c #FDFEFF",
"F+	c #060606",
"G+	c #FCFFFF",
"H+	c #000002",
"I+	c #000201",
"J+	c #615D5A",
"K+	c #FDFFFE",
"L+	c #FEFEFC",
"M+	c #FE0000",
"N+	c #FC6061",
"O+	c #FE0002",
"P+	c #FD5F5C",
"Q+	c #FF0101",
"R+	c #FE5F5B",
"S+	c #FF5D5E",
"T+	c #FE605F",
"U+	c #131313",
"V+	c #515151",
"W+	c #ADADAD",
"X+	c #A9A9A9",
"Y+	c #B6B6B6",
"Z+	c #D1D1D1",
"`+	c #F8F8F8",
" @	c #FFCC01",
".@	c #FFCC00",
"+@	c #FEDF60",
"@@	c #FEFFFD",
"#@	c #FFCC03",
"$@	c #FDE060",
"%@	c #FFCD00",
"&@	c #FECB00",
"*@	c #FFDF5E",
"=@	c #FFCB00",
"-@	c #FDE05E",
";@	c #FFFEFD",
">@	c #FFCA00",
",@	c #FCE160",
"'@	c #FFFDFE",
")@	c #FFFEFA",
"!@	c #FCFFFD",
"~@	c #FFFFFB",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                          .                                     .                                   .       .                 .                                                                                                                   ",
"                                                                                                                .     .     .   .             .   .   .           .     .                                                                                                                                                                         ",
"                                                                                                                  .       .       .   .   .         +   .                 .   .                                     .     .   .                                                                                                                   ",
"                                                                                                                        .           .   .       .           .       .             .   .                 .                   .                                                                                                                     ",
"                                                                                                                                                          .           . .   .       .         .     .                   .                                                                                                                         ",
"                                                                                                                      .                 @ # $               .     . .                 .                   .   .     .                                                                                                                             ",
"                                                                                                                  % & * + = - ; > - , . ' ) ! ~ - { . ] = >     = ^ > / - ( ~ - - - _ + :     :   < [   $ }     | ]   . .                                                                                                                         ",
"                                                                                                                1 2 3 4 5 6 7 8 9 0 a b c d e f g h i j k l m   n 7 j o p q r s t 7 - . u   v w x y z 8 A B   C D E                                                                                                                               ",
"                                                                                                                F E   G 5 9     9 5   H I . g f 7 J k j A   K   c     o L M N   c .     O , P Q c R S H T U & # g j                                                                                                                               ",
"                                                                                                                A j V W ( B 9 X Y Z ` 7 I   g 1 6 g N  .A . ..  +.9 j o ..@.=   #.      M $.%.C #.  f s P A e w &.j     .                                                                                                                         ",
"                                                                                                                *.@   #.=.9     -.5   ;.>.R ,.f 7 ! ..j A   k   '..   o f ' ).  c       $ 4 9   !.J ~.3 A b Z -.{.j       .                                                                                                                       ",
"                                                                                                                ].^./.(.5 _.Y :.9 =.. <.[.9 }.f 7   |.j 1.c P   +.Y F o f 2.3.  c   .     ,.:.  ' 4.5.6.A 7.h 8.{.j         .                                                                                                                     ",
"                                                                                                                  ! { .               . =.: .         .         .           .                     } 5         .     .   .                                                                                                                         ",
"                                                                                                                  .   .     .                           .   .           . .       .       .                                                                                                                                                       ",
"                                                                                                                          .                                                     .   .           .     .           .                                                                                                                               ",
"                                                                                                                                          .                     .                                                                                                                                                                                 ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                        .                               .                     .                                                                                         .   .                           .                                                                                         ",
"                                                                            .                                         .       .                                                                 .       .   .       .         .                 .   .   .                                                                                         ",
"                                                  .                                     .                           .                               .     .   .                                     .           .                                 .                                                                                               ",
"                                                    .                         .   .                   .                       .                         .                                         .           .   .                                       .   .                                                                                   ",
"                                        .                                             .                               .                             .                                               .   . .     .         .                     .           .                                                                                     ",
"                                                          .       .                       .                 .   .   .   .                             .                                           .           .       .                               .                                                                                           ",
"                                              .     . + /           .                       .     .   .               .     .                     .       .                                     .                   .                                                                                                                             ",
"                                            . R 9.| *.) 0._.a.* b..                       . 5 5 5 ]             ! = - , R     .                     .     [ +                                       { _             } $                                     { _                                                                                   ",
"                                          c.!.D d.% a.*.e.D O f.g._.p =.                    g.g.g.9             {.h.i.j._.:       .   .                   k.=.      .                             . l.G   .         m.*.        .   n.R                   . l.G     .                                                                             ",
"                                    .   . o.l.{.1   w p.q.g.w ~ r.s.t.x     .               g.g.g.9             {.g   + u.8..     .           .       .   v.(           +       .           .                 .                     +.5           .     .   .     .         .       .                                                             ",
"                                      . j w.O       1 x.g.g.>.    ^ 5.y.J .                 g.g.g.9             {.g     [.:.  #..   c . z.A.,.u.1 . z.B.C.h.5 J D.B.%.;   E.u.k F.* c w G.x H.u I.  w - J.w K.L.E   F r.  A.o.'.{ D.M.2 ~.I.H.o.f.  N.s O.P.w = J.Q.  R.3.. ` S.T.h p G.U.                                                        ",
"                                        H.[.!.R     : V.d.g.*   . f d g.U.                  g.g.g.9             {.D g W.u J   g.    g.  A W.$ m X.  V.7.R.g.5 f.c . 4 Q., D Y.;.m   g.I.@ D / e.Z.. `.f b  +^ M .+  Y {.I.++* y @+=.k., ~ #+$+:  +> H @.<.! 6 1 I c    .c   g %+9.q.# G &+                                                        ",
"                                      r g.*+a.-.(   C.g.g.d.I.  f o.) g.=+> .               g.g.g.9             -+6 I z.;+>+. d.    g.  T ,+  -+9 ! g.    y.5 '+D.b )+Z.] !+(.F.    g.. f 6   {.-.  6 f 7.u.  - 6   9 {.: *+D.~+    v.(   {+]+I ^+~.7 /+    6 L I '.  j #.. g I   w.5 =.w..                                                       ",
"                                  . =.V.(+g.m _+x.T.M.d.g.g.:+t U S i.v.j.C.                g.g.g.9             {.<+    U.,.  g.  . d.. A o . $.9 5 [+    v.5 l [.s 7 E   ; }+y._+  g.  f i.  {.9 . 6 f I g   - i.  9 {.. % s. +# . v.5   g.}+7 7 ^ 7 7 .   `.f 7.c    .c   g I   w.5 ( w.                                                        ",
"                                    i |+o g.g.i b.L d.g.g.g.(+$ 1+`.d.2+3 g.#               g.g.g.9             {.g   C !.m.  g.Y.> g.  A o   {.-.  h.{ ( 2+5 3 h . A *.I.m.  N z   g.  1 6   {.9   i.f I g   - 6   -.{.# ,+  s o . v.;   3+F.~ [.[ 7 7     i.f I U   ' '.. g I   w.=.5 w.  .                                                     ",
"                                  {.2+x 4+D.g.g.2+++g.d.g.g.q.j.g.g.;+o..+9 5+6+            g.g.g.9             {.{+v.4+l.7+  ,.L.K.g.* P o   -+9   8+B H.q.5 = +.H.*+P.=.n U +. .  d.  1 6   {.9   6 L I g   - 6   9 -+{ 3+q j.9+  0.;+G &.B T.O.+ 7 7     6 f { =+#.B.k   g I . ^+5 5 w.    .                                                   ",
"                                > 3.0+a+i.p.!+u.g.g.g.g.g.g.g.g.g.Z g.3 M.N @ U.            g.g.g.9                           R , R       .         . | J   .   * = _     R ^ !       .               .       .           * ^ J .   R =..   ( b+                  ] %       .                                                                     ",
"                                    a.2+;.d.%+{+/.M.t.g.g.g._.0.[.;+m.:+s.y.=               g.g.g.9                 .     .     .       .   .     .                 .   .               .                                 .       .   .                                 .                                                                         ",
"                                  r.[+Q.t.'.1.c+K n d+g.g.g.P.2+A.e+V *+i q ;+}             g.g.g.9                     .     .   .   .   .     .         .       .   .     .   .     .                 .             .             .                                 .                                                                           ",
"                                  6.^ V y./+{+H g.b s d.g.g.J.o =+W [+e.2+c.S 6+            g.g.g.9               R < C     .               . { - = (     n.:   b._       _ b.  .   .     . .       .               .       .   .       .                           .                                                                             ",
"                                    f+g+A y.)+h+O ] 3+g.d.g.i+n.j.m.l.q 4 :+= .             g.g.g.9               2 H.{ j+e.j+e.              !+_.l.[+k+  f.m.  g 7.      7.g           .         .   .                 . .   .   .     .                             .                                                                           ",
"                                  J _+7+k B Z.*+/ -.g.g.g.g.g.l+j d.m+2+U.r.n+              g.g.g.9               v.;   R.# R.#             . w.b   # 5+        g I       I g   .           .                                   .           .                     .                                                                               ",
"                                    R '+w.U.d.o+f+6  +9 g.s.:+`.p+c ++A v. .                g.g.g.9             d {+5.= m.Y.  m.] I.` q+_+    w.I   r+!+  r.F   O.I . V G.C.g   8.>.. F r.n.Z d W.E.  $ s+u d ]+                                                    .                                                                             ",
"                                    C b+, +.z   R.{.a 7 g.c.s.-+! | 3+K.] {                 g.g.g.9             n.v.^ R v.5   v.5 j *+9+}     w.6 g :+j   {.9   g I 9+_.=.W O.  9 {.  9 {.( g.c.v h.  E.p.=.1.A       .         .                                                                                                                 ",
"                                        }.>+$+r.o+Q.f }+d.P.# @+{.n+l+Q.b               t+  u+g.g.v+w+t+  w+x+t+. v.5 . v.5   v.5 j Z         w.A r.A.B _ {.9   g I {.m.  # g   9 {.  9 {.5 y.    g.  m.)   0 A                                                                                                                                   ",
"                                    .     : P f.Q @ 8.m.g.' e y+P.}.T             w+x+  w+x+u+g.z+A+  x+  t+  w+  k.5   k.=.  v.5  .9         w.I     5+6.$.9   g I U.9   r.g   9 -+  9 {.5 v..   g.  Z ) . /.A                                                                                                                                   ",
"                                      .     $+H a.  C B+g.p + 5 A.x p+  .   .   t+  t+w+x+  g.z+g.C+. t+D+  E+    D 5 . D b+n.F+5 j 9         w.b   R.{+~+-+9   O.I ]+u   U.g   9 f.  k -+( v.    g.  /.y   #.A                                                                                                                                   ",
"                                            >.z.)+Y.S.k.g.B+>.b F f.b.    .     x+. x+  E+G+H+g.I+J+x+K+  t+. x+  v.5   c 0.p.4+5 j 9         !+ +v.e+`   $.-.  g 7.Y.t O.L.<+  $.|+z t ' 5 v.    g.. ~+^+6 (+A                                                                                                                                   ",
"                                              .   Y.k+J.y 1+d+      .   .       . w+L+  t+x+M+M+M+N+K+x+L+  w+w+    .   + , *     .   .             . .               ~ ^ .   . . / =.  .       .     0+ .  '+P                                                                                                                                   ",
"                                                    .   .       .     .       .   w+  x+w+  O+M+M+P+  E+t+  t+    .   .           .       .     .       .     .     .             .     .     .     . S *+Z :+L                                                                                                                                   ",
"                                                          .   .     .       .   x+x+t+t+  w+Q+M+Q+R+      .   x+      .             .   .                               .   .         .               . n.< ]                                                                                                                                     ",
"                                          .                                   . x+w+x+      M+Q+O+S+D+  t+t+w+          .             .     ] :       ; - - - ;       .   .     .                   . _ : .                                                                                                                                       ",
"                                                                                            M+M+M+T+            .   .                        .c .     w U+`.6 k+.         .                           I c                 .                           .     .                                                                                     ",
"                                                                                            M+M+M+T+                    .   .       .       j c       o w .       .   .       .           .           r.'.  .                       .           .       . .   .                                                                                   ",
"                                                                                            M+M+M+T+            r.F   r.' . '+m G.Z.+ * s.G.s+c       o o       ~+..G.8++ 9.l D.e.- V+o.s   n.Y `.V R b g !.1.2.  F r.  F 7.$ Z w W.A   $ s+u W z.                                                                                                ",
"                                                                                            M+M+M+T+            {.9   {.o   `.@+$ ^+0+]+i.Y.Z.c       o @.9 9 G p.3.! 0.M ^ d.N.b+'+H $ n ~+Q.s+n.++6.7.*+| o+u.  9 {.  9 {.5 g.1+J.[+  x K.=.0.A                                                                                                 ",
"                                                                                            M+M+M+T+            {.9   {.w . 6 f   g I A '+. M #.      o q+ .E [ (+0+  }+m+- 3+    ' B+}._ . 4 )   6+5 I H.  f i.  9 $.. Y -+5 y..   g.. Z :.  S.A     .                                                                                           ",
"                                                                                            M+M+M+T+            {.9   {.h   6 f   O.b A o   W+'..     o o .   . _.1   }+s = ^+      X c+;+] p.'       I c   1 `.  9 -+  -.{.5 v.    g.  Z '   }+A .       .                                                                                       ",
"                                                                                            M+M+M+T+            {.%.  Q.o   i.f   g 7.f+K   @+c   .   o o       U X+  V+:.^ w.    d Y+. !+L d 0   2 n+I c   f i.  9 f.  2 $.( v.  . d.  /.o   K A     . .   .                                                                                     ",
"                                                                                            M+M+M+T+            Z+v.z B.l   6 1 . g I 5 !+^.T.'.    . o w        .h+q &+; - w.    U.V.O.0.C v h+^.`.! I c   f 6   $.B+!.n -+5 v.    g.  ~+^+6 (+A         .                                                                                       ",
"                                                                                            M+M+M+T+              $ :                   C [                     . n.^ R             $ { .     `+^ R               . > =.                1 j   s.P                                                                                                 ",
"                                                                                            M+M+M+T+                .               .   .                                 .     .         .     .   .               .               .   ~.|+m.h+L                                                                                                 ",
"                                                                                            M+M+M+T+                  .                                               .       .     .   .         .                               .       $ < J .                                                                                                 ",
"                                                                                            M+M+M+T+              .     . . .     .                                 .                 .               .                               .           .         . .                                                                                   ",
"                                                                                            M+M+M+T+                .   .               .   .                         . .               .           .             .     .                 .             .                                                                                         ",
"                                                                                            M+M+M+T+                                      +                                     .                                           .   .   .                         .                                                                                   ",
"                                                                                            M+M+M+T+              .                           .                     .         .   .       .                 .       .               .       .                                                                                                     ",
"                                                                                            M+M+M+T+                                                              .   .                     .                 .                       .   .         .                                                                                             ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                             @.@.@+@                                                                                                                                                                                                                                              ",
"                                                                                  @@         @.@#@$@    x+t+x+w+                                                                                                                                                                                                                                  ",
"                                                                                    x+x+  . %@.@&@*@x+  w+w+x+w+                                                                                                                                                                                                                                  ",
"                                                                                @@  w+.   t+ @=@.@-@w+  x+K+;@                                                                                                                                                                                                                                    ",
"                                                                                x+      t+x+>@.@#@,@x+w+D+w+'@w+                                                                                                                                                                                                                                  ",
"                                                                                      w+w+  w+  t+t+w+  t+. x+)@                                                                                                                                                                                                                                  ",
"                                                                                x+@@x+w+t+    w+    x+  L+t+  t+                                                                                                                                                                                                                                  ",
"                                                                                x+K+  !@  t+D+    w+w+  t+t+w+                                                                                                                                                                                                                                    ",
"                                                                                t+    w+x+~@    t+        w+  x+                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                                                                                  "};
/* XPM */
static char * mfo_logo_xpm[] = {
"49 70 187 2",
"  	c #FEFEFE",
". 	c #EDEDED",
"+ 	c #C7C7C7",
"@ 	c #B7B7B7",
"# 	c #BEBEBE",
"$ 	c #DCDCDC",
"% 	c #FDFDFD",
"& 	c #F0F0F0",
"* 	c #8D8D8D",
"= 	c #323232",
"- 	c #030303",
"; 	c #020202",
"> 	c #171717",
", 	c #646464",
"' 	c #CECECE",
") 	c #A1A1A1",
"! 	c #161616",
"~ 	c #5C5C5C",
"{ 	c #ECECEC",
"] 	c #FBFBFB",
"^ 	c #656565",
"/ 	c #292929",
"( 	c #7D7D7D",
"_ 	c #B0B0B0",
": 	c #C6C6C6",
"< 	c #BCBCBC",
"[ 	c #969696",
"} 	c #4F4F4F",
"| 	c #060606",
"1 	c #222222",
"2 	c #D6D6D6",
"3 	c #636363",
"4 	c #1B1B1B",
"5 	c #AAAAAA",
"6 	c #DDDDDD",
"7 	c #505050",
"8 	c #1A1A1A",
"9 	c #DEDEDE",
"0 	c #999999",
"a 	c #333333",
"b 	c #E7E7E7",
"c 	c #858585",
"d 	c #363636",
"e 	c #FAFAFA",
"f 	c #E8E8E8",
"g 	c #111111",
"h 	c #202020",
"i 	c #E9E9E9",
"j 	c #737373",
"k 	c #8F8F8F",
"l 	c #676767",
"m 	c #B8B8B8",
"n 	c #F8F8F8",
"o 	c #2A2A2A",
"p 	c #121212",
"q 	c #EAEAEA",
"r 	c #D0D0D0",
"s 	c #050505",
"t 	c #3B3B3B",
"u 	c #6A6A6A",
"v 	c #434343",
"w 	c #949494",
"x 	c #4B4B4B",
"y 	c #D3D3D3",
"z 	c #AFAFAF",
"A 	c #070707",
"B 	c #464646",
"C 	c #F7F7F7",
"D 	c #252525",
"E 	c #6F6F6F",
"F 	c #B2B2B2",
"G 	c #8A8A8A",
"H 	c #151515",
"I 	c #272727",
"J 	c #101010",
"K 	c #0A0A0A",
"L 	c #C9C9C9",
"M 	c #939393",
"N 	c #8E8E8E",
"O 	c #666666",
"P 	c #9C9C9C",
"Q 	c #8C8C8C",
"R 	c #2C2C2C",
"S 	c #CFCFCF",
"T 	c #2B2B2B",
"U 	c #2F2F2F",
"V 	c #D7D7D7",
"W 	c #ADADAD",
"X 	c #AEAEAE",
"Y 	c #BFBFBF",
"Z 	c #696969",
"` 	c #424242",
" .	c #080808",
"..	c #D9D9D9",
"+.	c #898989",
"@.	c #0C0C0C",
"#.	c #D2D2D2",
"$.	c #F2F2F2",
"%.	c #212121",
"&.	c #454545",
"*.	c #242424",
"=.	c #EFEFEF",
"-.	c #7C7C7C",
";.	c #BBBBBB",
">.	c #808080",
",.	c #9E9E9E",
"'.	c #848484",
").	c #B1B1B1",
"!.	c #989898",
"~.	c #FCFCFC",
"{.	c #0E0E0E",
"].	c #E5E5E5",
"^.	c #5D5D5D",
"/.	c #C3C3C3",
"(.	c #1E1E1E",
"_.	c #C0C0C0",
":.	c #606060",
"<.	c #C8C8C8",
"[.	c #585858",
"}.	c #343434",
"|.	c #555555",
"1.	c #040404",
"2.	c #CACACA",
"3.	c #3A3A3A",
"4.	c #0B0B0B",
"5.	c #DFDFDF",
"6.	c #EBEBEB",
"7.	c #3D3D3D",
"8.	c #A5A5A5",
"9.	c #818181",
"0.	c #CBCBCB",
"a.	c #797979",
"b.	c #A8A8A8",
"c.	c #F4F4F4",
"d.	c #1C1C1C",
"e.	c #F3F3F3",
"f.	c #393939",
"g.	c #4A4A4A",
"h.	c #F1F1F1",
"i.	c #F5F5F5",
"j.	c #919191",
"k.	c #1F1F1F",
"l.	c #616161",
"m.	c #E2E2E2",
"n.	c #373737",
"o.	c #B3B3B3",
"p.	c #7A7A7A",
"q.	c #E4E4E4",
"r.	c #C4C4C4",
"s.	c #E3E3E3",
"t.	c #9F9F9F",
"u.	c #787878",
"v.	c #C1C1C1",
"w.	c #5F5F5F",
"x.	c #595959",
"y.	c #E0E0E0",
"z.	c #262626",
"A.	c #565656",
"B.	c #B9B9B9",
"C.	c #878787",
"D.	c #838383",
"E.	c #9D9D9D",
"F.	c #B6B6B6",
"G.	c #767676",
"H.	c #1D1D1D",
"I.	c #353535",
"J.	c #727272",
"K.	c #A2A2A2",
"L.	c #9A9A9A",
"M.	c #828282",
"N.	c #383838",
"O.	c #0F0F0F",
"P.	c #F6F6F6",
"Q.	c #303030",
"R.	c #7E7E7E",
"S.	c #BABABA",
"T.	c #D1D1D1",
"U.	c #CCCCCC",
"V.	c #414141",
"W.	c #A7A7A7",
"X.	c #090909",
"Y.	c #282828",
"Z.	c #A0A0A0",
"`.	c #888888",
" +	c #545454",
".+	c #0D0D0D",
"++	c #6E6E6E",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                            . + @ # $ %                                           ",
"                                      & * = - ; ; ; ; > , '                                       ",
"                                    ) ! ; ; ; ; ; ; ; ; ; - ~ {                                   ",
"                                ] ^ ; ; ; / ( _ : < [ } | ; ; 1 2                                 ",
"                                3 ; ; 4 5 %             6 7 ; ; 8 9                               ",
"                              0 ; ; a b                     c ; ; d e                             ",
"                            f g ; h i                         j ; ; k                             ",
"                            l ; ; m                           n o ; p q                           ",
"                          r s ; t                               @ ; ; u                           ",
"                          v ; ; w                                 x ; | y                         ",
"                        z ; ; ; '                                 2 A ; B                         ",
"                      C D ; ; ; i                                   E ; ; F                       ",
"                      G ; ; ; ; f                                   . H ; I n                     ",
"                    f J ; K ; ; L                                     M ; ; N                     ",
"                    O ; ; P ; ; Q                                     e R ; p q                   ",
"                  S s ; }   T ; U V W W W W W W W W W W W W W W W X Y b m ; ; Z                   ",
"                  ` ;  ...  Q ; ; +.K ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; T @.; s #.                ",
"                X ; ; j     $.8 ; %.j ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; &.                ",
"              C *.; > =.      P ; ; -.r r r r r r r r r r r ;.>.>.,.m '.U ; ; ; ; ).              ",
"              +.; ; !.        ~.a ; {.].                    ^.; - /.      _ (.; ; I n             ",
"            b J ; U ]           _.; ; :.                  <.- ; [.          i }.; ; *             ",
"            l ; ; <               |.; 1.2.              % 3.; 4.5.            q h ; g 6.          ",
"          ].A ; }                 6 K ; 7.%             8.; ; -.                @ ; ; 9.          ",
"          * ; ; 0.                  a.; ; b.          c.(.; d.e.                  f.; *.          ",
"          g.; /                     h.8 ; %.i.        >.; ; )                     j.; ; 6         ",
"          k.; l.                      ,.; ; '.      m.@.; n.~.                    L ; ; o.        ",
"          4.; p.                      ~.}.; {.q.    ~ ; - r.                      s.; ; t.        ",
"          {.; u.                        v.- ; w.  + - ; x.                        y.; ; )         ",
"          z.; [.                          A.; 1.2.f.; 4.y.                        v.; ; B.        ",
"          |.; d.~.                        9 K @.C.; ; (                           D.; - b         ",
"          E.; ; F.                          p.G.(.; H.e.                        ] z.; }.          ",
"          h.g ; I.]                         $.J.; ; K.                          L.; ; [           ",
"            M.; ; u.                        # | ; N.%                         y O.; 1 P.          ",
"            C Q.; ; R.~.                  S.J ; K T.                        U.8 ; 1.S.            ",
"              $ 8 ; ; V.U.            f E s ; s W.                      =.>.X.; ; *               ",
"                ..Y.; ; ; I.G.0 E.D.x  .; ; ; } Z.Z.Z.Z.Z.Z.Z.Z.Z.,.`. +.+; ; | M                 ",
"                  $.++A ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; }.<.                  ",
"                      y.R.a | ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; 4 ~ F.%                     ",
"                            n m.$ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ 9 =.                            ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  ",
"                                                                                                  "};
